name: vegagrasp
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - absl-py=2.3.1=pyhd8ed1ab_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - cpp-expected=1.3.1=h171cf75_0
  - debugpy=1.8.17=py310h25320af_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h3385a95_0
  - fmt=12.0.0=h2b0788b_0
  - grpcio=1.74.1=py310h8f3b6d6_1
  - icu=73.2=h59595ed_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyha191276_0
  - ipython=8.37.0=pyh8f84b5b_0
  - ipywidgets=8.1.8=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - jupyterlab_widgets=3.0.16=pyhcf101f3_1
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250512.1=cxx17_hba17884_0
  - libarchive=3.8.2=h3ec8f01_0
  - libblas=3.9.0=39_h4a7cf45_openblas
  - libcblas=3.9.0=39_h0358290_openblas
  - libcurl=8.17.0=h4e3cde8_0
  - libdeflate=1.22=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgomp=15.2.0=h4751f2c_7
  - libgrpc=1.74.1=h3288cfb_1
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.9.0=39_h47877c9_openblas
  - libmamba=2.3.3=h09abcb8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.0=h5eee18b_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libpng=1.6.50=h421ea60_1
  - libprotobuf=6.31.1=h49aed37_2
  - libre2-11=2025.11.05=h7b12aa8_0
  - libsodium=1.0.20=h4ab18f5_0
  - libsolv=0.7.35=h9463b59_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.7.0=he137b08_1
  - libuuid=1.41.5=h5eee18b_0
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=hcb278e6_0
  - mamba=2.3.3=h4396525_2
  - markdown=3.10=pyhcf101f3_1
  - markupsafe=3.0.3=py310h3406613_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nlohmann_json-abi=3.12.0=h0f90c79_1
  - openjpeg=2.5.3=h55fea9a_1
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - protobuf=6.31.1=py310ha36e12e_2
  - psutil=7.1.3=py310h139afa4_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.19=h6fa692b_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=2_cp310
  - pyzmq=27.1.0=py310h4f33d48_0
  - re2=2025.11.05=h5301d42_0
  - readline=8.3=hc2a1206_0
  - reproc=14.2.5.post0=hb9d3cd8_0
  - reproc-cpp=14.2.5.post0=h5888daf_0
  - setuptools=80.9.0=py310h06a4308_0
  - simdjson=4.0.7=hb700be7_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=h2a70700_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tensorboard=2.20.0=pyhe01879c_0
  - tensorboard-data-server=0.7.0=py310hed992bd_3
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.2=py310h7c4b9e2_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - vulkan-headers=1.3.231.1=h924138e_0
  - vulkan-tools=1.4.328.1=h215f996_0
  - wayland=1.24.0=hdac8c69_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=py310h06a4308_0
  - widgetsnbextension=4.0.15=pyhd8ed1ab_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml-cpp=0.8.0=h3f2d84a_0
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - anyio==4.11.0
      - arm-pytorch-utilities==0.4.3
      - asttokens==3.0.1
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cloudpickle==3.1.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - dacite==1.9.2
      - docstring-parser==0.17.0
      - etils==1.13.0
      - fancycompleter==0.11.1
      - farama-notifications==0.0.4
      - fast-kinematics==0.2.2
      - filelock==3.20.0
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glfw==2.10.0
      - gymnasium==0.29.1
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.1.4
      - idna==3.11
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - lxml==6.0.2
      - mani-skill==3.0.0b21
      - markdown-it-py==4.0.0
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - mplib==0.1.1
      - mpmath==1.3.0
      - mujoco==3.3.7
      - networkx==3.4.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - opencv-python==4.11.0.86
      - pdbpp==0.11.7
      - pettingzoo==1.25.0
      - pillow==12.0.0
      - pynvml==13.0.1
      - pyopengl==3.1.10
      - pyparsing==3.2.5
      - pyperclip==1.11.0
      - pyrepl==0.11.4
      - pytorch-kinematics==0.7.6
      - pytorch-seed==0.2.0
      - pyyaml==6.0.3
      - requests==2.32.5
      - rich==14.2.0
      - sapien==3.0.1
      - scipy==1.15.3
      - shellingham==1.5.4
      - shtab==1.7.2
      - smmap==5.0.2
      - sniffio==1.3.1
      - sympy==1.14.0
      - tabulate==0.9.0
      - toppra==0.6.3
      - torch==2.9.1
      - tqdm==4.67.1
      - transforms3d==0.4.2
      - trimesh==4.9.0
      - triton==3.5.1
      - typeguard==4.4.4
      - typer-slim==0.20.0
      - tyro==0.9.35
      - urllib3==2.5.0
prefix: /home/xzhan742/miniconda3/envs/vegagrasp
